Identity-Training-App/Identity-Training-App/Controllers/AccessCheckerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Identity_Training_App.Controllers
{
    [Authorize]
    public class AccessCheckerController : Controller
    {
        [AllowAnonymous]
        public IActionResult AllAccess()
        {
            return View();
        }

        public IActionResult AuthorizedAccess()
        {
            return View();
        }
        [Authorize(Roles ="User")]
        public IActionResult UserAccess()
        {
            return View();
        }
        [Authorize(Roles = "User,Admin")]

        public IActionResult UserOrAdminAccess()
        {
            return View();
        }
        [Authorize(Policy ="Admin")]
        public IActionResult AdminAccess()
        {
            return View();
        }

        public IActionResult AdminCreateAccess()
        {
            return View();
        }

        public IActionResult AdminCreateEditDeleteAccess()
        {
            return View();
        }

        public IActionResult AdminCreateEditDeleteSuperUserAccess()
        {
            return View();
        }
    }
}

Identity-Training-App/Identity-Training-App/Controllers/RolesController.cs
using Identity_Training_App.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Identity_Training_App.Controllers
{

    public class RolesController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _usermanager;
        private readonly RoleManager<IdentityRole> _rolemanager;

        public RolesController(ApplicationDbContext db, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> rolemanager)
        {
            _db = db;
            _usermanager = userManager;
            _rolemanager = rolemanager;
        }
        public IActionResult Index()
        {
            var roles = _db.Roles.ToList();
            return View(roles);
        }

        [HttpGet]
        public IActionResult Upsert(string id)
        {
            if(String.IsNullOrEmpty(id))
            {
                return View();
            }
            else
            {
                //update
                var obj = _db.Roles.FirstOrDefault(u=>u.Id == id);
                return View(obj);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(IdentityRole roleObj)
        {
            if(await _rolemanager.RoleExistsAsync(roleObj.Name))
            {
                TempData[SD.Error] = "Role alredy exists.";
                return RedirectToAction(nameof(Index));
            }
            if(string.IsNullOrEmpty(roleObj.Id))
            {
                await _rolemanager.CreateAsync(new IdentityRole { Name = roleObj.Name});
                TempData[SD.Success] = "Role created!.";
            }
            else
            {

                var objRoleFromDb = _db.Roles.FirstOrDefault(u=>u.Id == roleObj.Id);
                if(objRoleFromDb == null)
                {
                    TempData[SD.Error] = "Role not found.";
                    return RedirectToAction(nameof(Index));
                }
                objRoleFromDb.Name = roleObj.Name;
                objRoleFromDb.NormalizedName = roleObj.Name.ToUpper();
                var result = await _rolemanager.UpdateAsync(objRoleFromDb);
                TempData[SD.Success] = "Role updated!";
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string id)
        {
            var roleToDelete = _db.Roles.FirstOrDefault(u=>u.Id==id);
            if(roleToDelete == null)
            {
                TempData[SD.Error] = "Role not found.";
                return RedirectToAction(nameof(Index));
            }
            var userRolesForThisRole = _db.UserRoles.Where(u => u.RoleId == id).Count();
            if(userRolesForThisRole>0)
            {
                TempData[SD.Error] = "Cannot delete this role, since there are users assigned to this role.";
                return RedirectToAction(nameof(Index));
            }
            await _rolemanager.DeleteAsync(roleToDelete);
            TempData[SD.Success] = "Deleted successfully.";
            return RedirectToAction(nameof(Index));
        }
    }
}

Identity-Training-App/Identity-Training-App/Controllers/UserController.cs
using Identity_Training_App.Data;
using Identity_Training_App.Models;
using Identity_Training_App.Models.View_Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Identity_Training_App.Controllers
{
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _usermanager;

        public UserController(ApplicationDbContext db,UserManager<IdentityUser> userManager)
        {
            _db = db;
            _usermanager = userManager;
        }
        public IActionResult Index()
        {
            var userlist = _db.ApplicationUser.ToList();
            var userRole = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();
            foreach(var user in userlist)
            {
                var role = userRole.FirstOrDefault(u=> u.UserId == user.Id);
                if(role == null)
                {
                    user.Role = "None";
                }
                else
                {
                    user.Role = roles.FirstOrDefault(u=> u.Id == role.RoleId).Name;
                }
            }
            return View(userlist);
        }

        [HttpGet]
        public IActionResult Edit(string userId)
        {
            var objFromDb = _db.ApplicationUser.FirstOrDefault(u => u.Id == userId);
            if(objFromDb == null)
            {
                return NotFound();
            }
            var userRole = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();
            var role = userRole.FirstOrDefault(u=>u.UserId == userId);
            if(role != null)
            {
                objFromDb.RoleId = roles.FirstOrDefault(u => u.Id == role.RoleId).Id;
            }
            objFromDb.RoleList = _db.Roles.Select(u=> new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
            {
                Text = u.Name,
                Value = u.Id
            });
            return View(objFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ApplicationUser user)
        {
            if(ModelState.IsValid)
            {
                var objFromDb = _db.ApplicationUser.FirstOrDefault(u => u.Id == user.Id);
                if (objFromDb.Email != user.Email)
                {
                    var userWithChosenEmail = _db.Users.FirstOrDefault(u => u.Email == user.Email);
                    if(userWithChosenEmail != null && userWithChosenEmail.Id != objFromDb.Id || user.Email == null)
                    {
                        TempData[SD.Error] = "Chosen email is already in use.";
                        user.RoleList = _db.Roles.Select(u => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
                        {
                            Text = u.Name,
                            Value = u.Id
                        });
                        return View(user);
                    }
                    
                }
                    
                    if (objFromDb == null)
                    {
                        return NotFound();
                    }
                    var userRole = _db.UserRoles.FirstOrDefault(u => u.UserId == objFromDb.Id);
                    if (userRole != null)
                    {
                        var previousName = _db.Roles.Where(u => u.Id == userRole.RoleId).Select(e => e.Name).FirstOrDefault();
                        await _usermanager.RemoveFromRoleAsync(objFromDb, previousName);
                    }

                    await _usermanager.AddToRoleAsync(objFromDb, _db.Roles.FirstOrDefault(u => u.Id == user.RoleId).Name);
                    objFromDb.Name = user.Name;
                    objFromDb.Email = user.Email;
                objFromDb.EmailConfirmed = false;
                    _db.SaveChanges();
                TempData[SD.Success] = "User updated!";
                return RedirectToAction(nameof(Index));

                
            }
            TempData[SD.Error] = "Something went wrong.";
            user.RoleList = _db.Roles.Select(u => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
            {
                Text = u.Name,
                Value = u.Id
            });
            return View(user);
        }

        [HttpPost]
        public IActionResult LockUnlock(string userId)
        {
            var objFromDb = _db.ApplicationUser.FirstOrDefault(u => u.Id == userId);
            if (objFromDb == null)
            {
                return NotFound();
            }
            if(objFromDb.LockoutEnd!=null && objFromDb.LockoutEnd > DateTime.Now)
            {
                //unlock
                objFromDb.LockoutEnd = DateTime.Now;
                TempData[SD.Success] = "User unlocked!";
            }
            else
            {
                //user not locked, locking him
                objFromDb.LockoutEnd = DateTime.Now.AddYears(1000);
                TempData[SD.Success] = "User locked!";
            }
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Delete(string userId)
        {
            var user = _db.ApplicationUser.FirstOrDefault(u=>u.Id == userId);
            if(user == null)
            {
                return NotFound();
            }
            _db.ApplicationUser.Remove(user);
            _db.SaveChanges();
            TempData[SD.Success] = "User deleted!";
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> ManageUserClaims(string userId)
        {
            var user = await _usermanager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound();
            }

            var existingUserClaims = await _usermanager.GetClaimsAsync(user);

            var model = new UserClaimsVM()
            {
                UserId = userId
            };

            foreach(Claim claim in ClaimStore.claimsList)
            {
                UserClaim userClaim = new UserClaim()
                {
                    ClaimType = claim.Type
                };
                if(existingUserClaims.Any(c=>c.Type == claim.Type))
                {
                    userClaim.IsSelected = true;
                }
                model.userClaims.Add(userClaim);
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageUserClaims(UserClaimsVM userClaimsVM)
        {
            var user = await _usermanager.FindByIdAsync(userClaimsVM.UserId);
            if (user == null)
            {
                return NotFound();
            }

            var claims = await _usermanager.GetClaimsAsync(user);
            var result = await _usermanager.RemoveClaimsAsync(user,claims);

            if(!result.Succeeded)
            {
                TempData[SD.Error] = "Error while updating claims.";
                return View(userClaimsVM);

            }

            result = await _usermanager.AddClaimsAsync(user, userClaimsVM.userClaims.
                Where(c => c.IsSelected == true).
                Select(c => new Claim(c.ClaimType, c.IsSelected.ToString())));

            if(!result.Succeeded)
            {
                TempData[SD.Error] = "Error while updating claims.";
                return View(userClaimsVM);
            }

            TempData[SD.Success] = "Claims updated successfully.";
            return RedirectToAction(nameof(Index));
        }
    }
}

Identity-Training-App/Identity-Training-App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Identity_Training_App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Identity_Training_App.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" crossorigin="anonymous" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Identity_Training_App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Access Checker
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="AccessChecker" asp-action="AllAccess">All Access</a>
                                <a class="dropdown-item" asp-controller="AccessChecker" asp-action="AuthorizedAccess">Authorized Access</a>
                                <a class="dropdown-item" asp-controller="AccessChecker" asp-action="UserAccess">User Access</a>
                                <a class="dropdown-item" asp-controller="AccessChecker" asp-action="UserOrAdminAccess">UserORAdmin Access</a>
                                <a class="dropdown-item" asp-controller="AccessChecker" asp-action="UserANDAdminAccess">UserANDAdmin Access</a>
                                <a class="dropdown-item" asp-controller="AccessChecker" asp-action="AdminAccess">Admin Access</a>
                                <a class="dropdown-item" asp-controller="AccessChecker" asp-action="AdminCreateAccess">Admin - Create only Claim Access</a>
                                <a class="dropdown-item" asp-controller="AccessChecker" asp-action="AdminCreateEditDeleteAccess">Admin - Create,Edit & Delete Claim Access</a>
                                <a class="dropdown-item" asp-controller="AccessChecker" asp-action="AdminCreateEditDeleteSuperUserAccess">Admin - Create,Edit & Delete Claim Access || Super Admin</a>
                                <a class="dropdown-item" asp-controller="AccessChecker" asp-action="OnlyBhrugen">Only Bhrugen</a>
                                <a class="dropdown-item" asp-controller="AccessChecker" asp-action="FirstNameAuth">Check First Name Access</a>
                            </div>
                        </li>
                    </ul>
                    <partial name="_LoginPartialCustom"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Identity_Training_App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Identity-Training-App/Identity-Training-App/Views/Shared/_LoginPartialCustom.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


<ul class="navbar-nav">
    @if(SignInManager.IsSignedIn(User))
    {
     <li class="nav-item">
         <a class="nav-link" href="#"> Hello @UserManager.GetUserName(User)</a>
    </li>
    <li class="nav-item">
        <form id="logout-form" method="post" class="form-inline" asp-controller="Account" asp-action="Logoff">
            <button type="submit" class="btn nav-link">Logout</button>
        </form>
    </li>
    }
    else
    {
     <li class="nav-item">
        <a class="nav-link" asp-controller="Account" asp-action="Register">Register</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
    </li>
    }   
</ul>

Identity-Training-App/Identity-Training-App/Views/Shared/_Notification.cshtml
@if (TempData[SD.Success] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData[SD.Success]');
    </script>
}
@if (TempData[SD.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData[SD.Error]');
    </script>
}